branch-defaults:
  main:
    environment: null
environment-defaults:
  reactnd-contacts-server-dev:
    branch: null
    repository: null
global:
  application_name: reactnd-contacts-server
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
