version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  eb-Deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          name: Deploy on aws
          command: |
            eb deploy reactnd-contacts-server-dev
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - eb-Deploy
